{
  "entity": {
    "location": {
      "namespaceTitle": "Uno.Threading",
      "namespaceUri": "uno/threading",
      "packageName": "Uno.Threading",
      "packageVersion": "1.8.0-rc1"
    },
    "parameters": [
      {
        "name": "failure",
        "href": "uno/action_1",
        "title": "Action<Exception> (Exception)",
        "fullyQualifiedTitle": "Uno.Action<Uno.Exception> (Uno.Exception)"
      }
    ],
    "returns": {
      "href": "uno/threading/future_1",
      "title": "Future<T>",
      "fullyQualifiedTitle": "Uno.Threading.Future<T>"
    },
    "id": {
      "id": "uno/threading/future_1/catch_c9ac53e1",
      "parentId": "uno/threading/future_1",
      "type": "Method",
      "modifiers": [
        "public"
      ]
    },
    "uri": {
      "idUri": "uno/threading/future_1/catch_c9ac53e1",
      "href": "uno/threading/future_1/catch_c9ac53e1"
    },
    "titles": {
      "pageTitle": "Future.Catch Method (Action<Exception> (Exception))",
      "navigationTitle": "Catch Method (Action<Exception> (Exception))",
      "fullTitle": "Uno.Threading.Future`1.Catch",
      "indexTitle": "Catch(Action<Exception> (Exception))",
      "fullyQualifiedIndexTitle": "Uno.Threading.Future.Catch(Uno.Action<Uno.Exception> (Uno.Exception))"
    },
    "syntax": {
      "uno": "public Uno.Threading.Future<T> Catch(Uno.Action<Uno.Exception> (Uno.Exception) failure) {}"
    }
  },
  "tableOfContents": {}
}